### ISSUE TITLE
ESP32 import errors

### ISSUE THREAD

**Issue by chopeks** [microhomie/microhomie#37]
Hello.
I'm struggling a bit trying to make samples work with newest micropython firmware. But it seems to have some problem, that isn't obvious to me. I'm not sure if that's library issue or micropython issue though. FS structure attached. 
![structure](https://user-images.githubusercontent.com/37939738/62423824-670a0300-b6c6-11e9-89ab-55167a804855.png)

```>>> exec(open('./main.py').read(),globals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in <module>
ImportError: cannot import name HomieDevice
```

**Comment by chopeks** [comment]
Ok, it seems that my ESP32 has some hardware issue, I've replaced it with a new one. Works now. Sorry for disturbing ;)
